name: Build & Upload Artifact

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_release:
    name: Release build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            windows-latest,
          ]
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v6

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - name: Build Release
        shell: bash
        run: |
          cargo build --verbose --release
      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" == "Windows" ]; then EXT=".exe"; fi
          cp "target/release/anipure$EXT" "dist/anipure-${{ runner.arch }}-${{ runner.os }}$EXT"
      - name: Export executable
        uses: actions/upload-artifact@v7
        with:
          name: anipure-${{ runner.arch }}-${{ runner.os }}
          compression-level: 9
          path: dist/anipure-*
